# Generated by Django 3.2.6 on 2022-11-10 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coldbeverage', models.CharField(max_length=250)),
                ('Breakfast', models.IntegerField(default=0)),
                ('SpecialDosavarieties', models.IntegerField(default=0)),
                ('Ravadosas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=250)),
                ('quentity', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('ondelete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swiggy.category')),
            ],
        ),
    ]
