# Generated by Django 3.2.6 on 2022-11-17 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0002_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='ondelete',
        ),
    ]
