# Generated by Django 4.1.3 on 2022-11-21 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swiggy', '0004_food_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='quality',
        ),
    ]
